import { execFile as execFileCallback } from "node:child_process";
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";
import {
  archiveDoneTasks,
  completeTask,
} from "../../application/tasks/archive-tasks.js";
import { checkpointTask } from "../../application/tasks/checkpoint-task.js";
import { listTasks } from "../../application/tasks/list-tasks.js";
import { verifyTask } from "../../application/tasks/verify-task.js";
import {
  atlasPath,
  enginePath,
  PROJECTS_DIR,
  resolveWithin,
} from "../../paths.js";

const execFile = promisify(execFileCallback);

// Re-exported for existing importers (daily/context commands, tests). The
// implementation and the MCP server both live in the application layer now.
export { listTasks };

export async function runTasksCommand(
  action: string,
  args: string[],
): Promise<void> {
  const projectIndex = args.indexOf("--project");
  const projectId = projectIndex >= 0 ? args[projectIndex + 1] : "atlas";
  if (!projectId) throw new Error("--project requires a project id");
  if (action === "list") {
    const state = args.find(
      (arg, index) => !arg.startsWith("--") && index !== projectIndex + 1,
    );
    console.log(JSON.stringify(await listTasks(state, projectId), null, 2));
    return;
  }
  if (action === "doctor") {
    try {
      const result = await execFile(process.execPath, [
        enginePath("scripts", "validate-tasks.mjs"),
        resolveWithin(atlasPath(PROJECTS_DIR), projectId, "tasks"),
      ]);
      process.stdout.write(result.stdout);
    } catch (error) {
      const failure = error as Error & { stdout?: string; stderr?: string };
      if (failure.stdout) process.stdout.write(failure.stdout);
      if (failure.stderr) process.stderr.write(failure.stderr);
      process.exitCode = 1;
    }
    return;
  }
  if (action === "index") {
    const tasks = await listTasks(undefined, projectId);
    const body = [
      "# Tasks",
      "",
      "<!-- Generated by `ocean tasks index --write`. Do not edit by hand. -->",
      "",
      "| ID | State | Title | Goal |",
      "|---|---|---|---|",
      ...tasks.map(
        (task) =>
          `| ${task.id} | ${task.state} | ${task.title.replaceAll("|", "\\|")} | ${task.goal.replaceAll("|", "\\|")} |`,
      ),
      "",
    ].join("\n");
    const target = resolveWithin(
      atlasPath(PROJECTS_DIR),
      projectId,
      "index.md",
    );
    if (args.includes("--write")) {
      await writeFile(target, body, "utf8");
      console.log(`wrote ${path.relative(atlasPath(), target)}`);
    } else process.stdout.write(body);
    return;
  }
  if (action === "checkpoint") {
    const id = args.find((arg) => !arg.startsWith("--"));
    const noteIndex = args.indexOf("--note");
    const nextIndex = args.indexOf("--next");
    if (!id || noteIndex < 0 || !args[noteIndex + 1])
      throw new Error(
        "Usage: ocean tasks checkpoint <id> --note <text> [--next <text>] [--project <id>]",
      );
    const result = await checkpointTask(
      id,
      resolveWithin(atlasPath(PROJECTS_DIR), projectId, "tasks"),
      {
        note: args[noteIndex + 1],
        next: nextIndex >= 0 ? args[nextIndex + 1] : undefined,
      },
    );
    console.log(JSON.stringify({ ...result, project: projectId }, null, 2));
    return;
  }
  if (action === "verify") {
    const id = args.find((arg) => !arg.startsWith("--"));
    if (!id) {
      console.error("Usage: ocean tasks verify <id> [--project <id>]");
      process.exitCode = 1;
      return;
    }
    const outcome = await verifyTask(
      id,
      resolveWithin(atlasPath(PROJECTS_DIR), projectId, "tasks"),
    );
    console.log(JSON.stringify(outcome, null, 2));
    if (!outcome.passed) process.exitCode = 1;
    return;
  }
  if (action === "complete") {
    const id = args[0];
    if (!id) {
      console.error("Usage: ocean tasks complete <id>");
      process.exitCode = 1;
      return;
    }
    try {
      console.log(
        JSON.stringify(
          await completeTask(
            id,
            resolveWithin(atlasPath(PROJECTS_DIR), projectId, "tasks"),
            { verify: !args.includes("--no-verify") },
          ),
          null,
          2,
        ),
      );
    } catch (error) {
      console.error(error instanceof Error ? error.message : String(error));
      process.exitCode = 1;
    }
    return;
  }
  if (action !== "archive") {
    console.error(
      "Usage: ocean tasks list [state] [--project <id>]|doctor|index [--write]|checkpoint <id> --note <text> [--next <text>]|verify <id>|complete <id>|archive [--apply|--auto]",
    );
    process.exitCode = 1;
    return;
  }
  const apply = args.includes("--apply") || args.includes("--auto");
  const result = await archiveDoneTasks(
    resolveWithin(atlasPath(PROJECTS_DIR), projectId, "tasks"),
    apply,
  );
  console.log(JSON.stringify({ dryRun: !apply, ...result }, null, 2));
}
