import { archiveDoneTickets, completeTicket } from "../../application/tickets/archive-tickets.js";
import { readdir, readFile } from "node:fs/promises";
import { execFile as execFileCallback } from "node:child_process";
import { promisify } from "node:util";
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { atlasPath, enginePath, resolveWithin } from "../../paths.js";

const execFile = promisify(execFileCallback);

export type TicketSummary = { id: string; title: string; state: string; goal: string; updatedAt: string };

export async function listTickets(state?: string, projectId = "atlas"): Promise<TicketSummary[]> {
  const root = resolveWithin(atlasPath("projects"), projectId, "tickets");
  const records: TicketSummary[] = [];
  let entries;
  try { entries = await readdir(root, { withFileTypes: true }); } catch { return records; }
  for (const entry of entries) {
    if (!entry.isDirectory() || entry.name === "archive") continue;
    const file = path.join(root, entry.name, "task.md");
    let source: string;
    try { source = await readFile(file, "utf8"); } catch { continue; }
    const fields = Object.fromEntries(source.slice(0, source.indexOf("\n---", 4)).split("\n").slice(1)
      .filter((line) => /^[\w-]+:/.test(line)).map((line) => { const index = line.indexOf(":"); return [line.slice(0, index), line.slice(index + 1).trim()]; }));
    if (state && fields.state !== state) continue;
    records.push({ id: fields.id ?? entry.name, title: fields.title ?? "", state: fields.state ?? "", goal: fields.goal ?? "", updatedAt: fields.updated_at ?? "" });
  }
  return records.sort((a, b) => a.id.localeCompare(b.id));
}

export async function runTicketsCommand(action: string, args: string[]): Promise<void> {
  const projectIndex = args.indexOf("--project");
  const projectId = projectIndex >= 0 ? args[projectIndex + 1] : "atlas";
  if (!projectId) throw new Error("--project requires a project id");
  if (action === "list") {
    const state = args.find((arg, index) => !arg.startsWith("--") && index !== projectIndex + 1);
    console.log(JSON.stringify(await listTickets(state, projectId), null, 2));
    return;
  }
  if (action === "doctor") {
    try {
      const result = await execFile(process.execPath, [enginePath("scripts", "validate-tickets.mjs"), resolveWithin(atlasPath("projects"), projectId, "tickets")]);
      process.stdout.write(result.stdout);
    } catch (error) {
      const failure = error as Error & { stdout?: string; stderr?: string };
      if (failure.stdout) process.stdout.write(failure.stdout);
      if (failure.stderr) process.stderr.write(failure.stderr);
      process.exitCode = 1;
    }
    return;
  }
  if (action === "index") {
    const tickets = await listTickets(undefined, projectId);
    const body = ["# Tickets", "", "<!-- Generated by `atlas tickets index --write`. Do not edit by hand. -->", "", "| ID | State | Title | Goal |", "|---|---|---|---|", ...tickets.map((ticket) => `| ${ticket.id} | ${ticket.state} | ${ticket.title.replaceAll("|", "\\|")} | ${ticket.goal.replaceAll("|", "\\|")} |`), ""].join("\n");
    const target = resolveWithin(atlasPath("projects"), projectId, "index.md");
    if (args.includes("--write")) { await writeFile(target, body, "utf8"); console.log(`wrote ${path.relative(atlasPath(), target)}`); }
    else process.stdout.write(body);
    return;
  }
  if (action === "checkpoint") {
    const id = args.find((arg) => !arg.startsWith("--"));
    const noteIndex = args.indexOf("--note");
    const nextIndex = args.indexOf("--next");
    if (!id || noteIndex < 0 || !args[noteIndex + 1]) throw new Error("Usage: atlas tickets checkpoint <id> --note <text> [--next <text>] [--project <id>]");
    const target = resolveWithin(atlasPath("projects"), projectId, "tickets", id, "task.md");
    let source = await readFile(target, "utf8");
    const entry = `- ${new Date().toISOString().slice(0, 10)} — ${args[noteIndex + 1]}`;
    if (/^## Log\s*$/m.test(source)) source = source.replace(/^## Log\s*$/m, `## Log\n\n${entry}`);
    else source = `${source.trimEnd()}\n\n## Log\n\n${entry}\n`;
    const next = nextIndex >= 0 ? args[nextIndex + 1] : undefined;
    if (next) {
      if (/^## Next action\s*$/m.test(source)) source = source.replace(/^## Next action\s*$[\s\S]*?(?=^## |\s*$)/m, `## Next action\n\n${next}\n\n`);
      else source = `${source.trimEnd()}\n\n## Next action\n\n${next}\n`;
    }
    await writeFile(target, source, "utf8");
    console.log(JSON.stringify({ checkpointed: id, project: projectId }, null, 2));
    return;
  }
  if (action === "complete") {
    const id = args[0];
    if (!id) {
      console.error("Usage: atlas tickets complete <id>");
      process.exitCode = 1;
      return;
    }
    try { console.log(JSON.stringify(await completeTicket(id, resolveWithin(atlasPath("projects"), projectId, "tickets")), null, 2)); }
    catch (error) { console.error(error instanceof Error ? error.message : String(error)); process.exitCode = 1; }
    return;
  }
  if (action !== "archive") {
    console.error("Usage: atlas tickets list [state] [--project <id>]|doctor|index [--write]|checkpoint <id> --note <text> [--next <text>]|complete <id>|archive [--apply|--auto]");
    process.exitCode = 1;
    return;
  }
  const apply = args.includes("--apply") || args.includes("--auto");
  const result = await archiveDoneTickets(resolveWithin(atlasPath("projects"), projectId, "tickets"), apply);
  console.log(JSON.stringify({ dryRun: !apply, ...result }, null, 2));
}
